#!/bin/bash -ex

export UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1
export FUZZ_CONFIGS=1
export AFL_NO_UI=1

prefix=conf-fuzz

for (( i = 0; i < $(nproc); i++ )); do
    afl_type=-S
    num=$(printf '%02d' "$i")
    (( i == 0 )) && afl_type=-M
    config_dir=fuzz/configs/generated/"$num"

    mkdir -p -- "$config_dir"
    FUZZ_CONFIGS="$config_dir"/psi-notify \
	afl-fuzz -i fuzz/configs/testcases -o fuzz/configs/results -f "$config_dir"/psi-notify -m none \
	"$afl_type" "$prefix-$num" ./psi-notify &
done

wait
